export const ENTITIES = [
  {
    idField: 'id',
    multiSaveUrl: 'id_rules/update_multiple',
    fixedColumns: 4,
    idType: 'uuid',
    titleField: 'name',
    extEntity: false,
    description: '자동생성 ID 룰 정의',
    active: false,
    tableName: 'id-rules',
    name: 'IdRule',
    searchUrl: 'id-rules',
    bundle: 'dev'
  },
  {
    idField: 'id',
    multiSaveUrl: 'terminologies/update_multiple',
    fixedColumns: 4,
    idType: 'uuid',
    titleField: 'name',
    extEntity: false,
    description: '용어',
    active: false,
    tableName: 'terminologies',
    name: 'Terminology',
    searchUrl: 'terminologies',
    bundle: 'msg'
  },
  {
    idField: 'id',
    multiSaveUrl: 'messages/update_multiple',
    fixedColumns: 4,
    idType: 'uuid',
    titleField: 'name',
    extEntity: false,
    description: '메시지',
    active: false,
    tableName: 'messages',
    name: 'Message',
    searchUrl: 'messages',
    bundle: 'msg'
  },
  {
    idField: 'id',
    multiSaveUrl: 'permissions/update_multiple',
    fixedColumns: 0,
    idType: 'uuid',
    extEntity: false,
    name: 'Permission',
    description: '권한',
    active: false,
    searchUrl: 'permissions',
    bundle: 'sec',
    tableName: 'permissions'
  },
  {
    idField: 'id',
    multiSaveUrl: 'users_roles/update_multiple',
    fixedColumns: 0,
    idType: 'uuid',
    extEntity: false,
    name: 'UsersRole',
    description: '사용자 역할 관계',
    active: false,
    searchUrl: 'users-roles',
    bundle: 'sec',
    tableName: 'users-roles'
  },
  {
    idField: 'id',
    multiSaveUrl: 'request_auths/update_multiple',
    fixedColumns: 0,
    idType: 'uuid',
    titleField: 'title',
    extEntity: false,
    description: '사용자 / 권한 요청',
    active: false,
    tableName: 'request-auths',
    name: 'RequestAuth',
    searchUrl: 'request-auths',
    bundle: 'sec'
  },
  {
    idField: 'id',
    multiSaveUrl: 'roles/update_multiple',
    fixedColumns: 4,
    idType: 'uuid',
    titleField: 'name',
    extEntity: false,
    description: '역할',
    active: false,
    tableName: 'roles',
    name: 'Role',
    searchUrl: 'roles',
    bundle: 'sec'
  },
  {
    idField: 'id',
    multiSaveUrl: 'diy_templates/update_multiple',
    fixedColumns: 4,
    idType: 'uuid',
    titleField: 'name',
    extEntity: false,
    description: '커스텀 템플릿',
    active: false,
    tableName: 'diy-templates',
    name: 'DiyTemplate',
    searchUrl: 'diy-templates',
    bundle: 'dev'
  },
  {
    idField: 'id',
    multiSaveUrl: 'domain_apps/update_multiple',
    fixedColumns: 0,
    idType: 'uuid',
    titleField: 'name',
    extEntity: false,
    description: '도메인 애플리케이션',
    active: false,
    tableName: 'domain-apps',
    name: 'DomainApp',
    searchUrl: 'domain-apps',
    bundle: 'core'
  },
  {
    idField: 'id',
    multiSaveUrl: 'common_codes/update_multiple',
    fixedColumns: 4,
    idType: 'uuid',
    titleField: 'name',
    extEntity: false,
    description: '공통코드',
    active: false,
    tableName: 'common-codes',
    name: 'Code',
    searchUrl: 'common-codes',
    bundle: 'core'
  },
  {
    idField: 'id',
    multiSaveUrl: 'attachments/update_multiple',
    fixedColumns: 3,
    idType: 'uuid',
    titleField: 'name',
    extEntity: false,
    description: '첨부파일',
    active: false,
    tableName: 'attachments',
    name: 'Attachment',
    searchUrl: 'attachments',
    bundle: 'core'
  },
  {
    idField: 'id',
    multiSaveUrl: 'storage_infos/update_multiple',
    fixedColumns: 4,
    idType: 'uuid',
    titleField: 'name',
    extEntity: false,
    description: '첨부파일 저장소',
    active: false,
    tableName: 'storage-infos',
    name: 'Storage',
    searchUrl: 'storage-infos',
    bundle: 'core'
  },
  {
    idField: 'id',
    multiSaveUrl: 'data_srcs/update_multiple',
    fixedColumns: 3,
    idType: 'uuid',
    titleField: 'name',
    extEntity: false,
    description: '데이터 소스',
    active: false,
    tableName: 'data-srcs',
    name: 'DataSrc',
    searchUrl: 'data-srcs',
    bundle: 'core'
  },
  {
    idField: 'id',
    multiSaveUrl: 'properties/update_multiple',
    fixedColumns: 4,
    idType: 'uuid',
    titleField: 'name',
    extEntity: false,
    description: '확장 프로퍼티',
    active: false,
    tableName: 'properties',
    name: 'Property',
    searchUrl: 'properties',
    bundle: 'core'
  },
  {
    idField: 'id',
    multiSaveUrl: 'diy_services/update_multiple',
    fixedColumns: 4,
    idType: 'uuid',
    titleField: 'name',
    extEntity: false,
    description: '커스텀 서비스',
    active: false,
    tableName: 'diy-services',
    name: 'DiyService',
    searchUrl: 'diy-services',
    bundle: 'dev'
  },
  {
    idField: 'id',
    multiSaveUrl: 'entities/update_multiple',
    fixedColumns: 4,
    idType: 'uuid',
    titleField: 'name',
    extEntity: false,
    description: '엔티티',
    active: false,
    tableName: 'entities',
    name: 'Entity',
    searchUrl: 'entities',
    bundle: 'base'
  },
  {
    idField: 'id',
    fixedColumns: 4,
    idType: 'uuid',
    titleField: 'name',
    delStrategy: 'restrict_with_error',
    extEntity: false,
    description: '엔티티 컬럼',
    association: 'one-to-many',
    active: false,
    dataProp: 'columns',
    tableName: 'entity-columns',
    masterId: '29e3ce82-9507-4aec-80fb-4523319c3bd6',
    refField: 'entityId',
    name: 'ResourceColumn',
    searchUrl: 'entity-columns',
    bundle: 'base'
  },
  {
    idField: 'id',
    multiSaveUrl: 'menu_details/{id}/menu_detail_columns/update_multiple',
    fixedColumns: 4,
    idType: 'uuid',
    titleField: 'name',
    delStrategy: 'delete',
    extEntity: false,
    description: '메뉴 상세 화면 컬럼',
    association: 'one-to-many',
    active: false,
    dataProp: 'columns',
    tableName: 'menu-detail-columns',
    masterId: '5261c607-7365-4fae-9352-26b2b2044171',
    refField: 'menuDetailId',
    name: 'MenuDetailColumn',
    searchUrl: 'menu-details/{id}/menu-detail-columns',
    bundle: 'base'
  },
  {
    idField: 'id',
    multiSaveUrl: 'menu_details/{id}/menu_detail_buttons/update_multiple',
    fixedColumns: 4,
    idType: 'uuid',
    titleField: 'name',
    delStrategy: 'delete',
    extEntity: false,
    description: '메뉴 상세 화면 버튼',
    association: 'one-to-many',
    active: false,
    dataProp: 'buttons',
    tableName: 'menu-detail-buttons',
    masterId: '5261c607-7365-4fae-9352-26b2b2044171',
    refField: 'menuDetailId',
    name: 'MenuDetailButton',
    searchUrl: 'menu-details/{id}/menu-detail-buttons',
    bundle: 'base'
  },
  {
    idField: 'id',
    multiSaveUrl: 'menus/{id}/menu_columns/update_multiple',
    fixedColumns: 4,
    idType: 'uuid',
    titleField: 'name',
    delStrategy: 'delete',
    extEntity: false,
    description: '메뉴 컬럼',
    association: 'one-to-many',
    active: false,
    dataProp: 'columns',
    tableName: 'menu-columns',
    masterId: 'edf11f36-ae31-4b01-af6e-60449ff7d24a',
    refField: 'menuId',
    name: 'MenuColumn',
    searchUrl: 'menu/{id}/menu-columns',
    bundle: 'base'
  },
  {
    idField: 'id',
    multiSaveUrl: 'ranged_seqs/update_multiple',
    fixedColumns: 3,
    idType: 'uuid',
    extEntity: false,
    description: '범위내 시퀀스 관리',
    active: false,
    tableName: 'ranged-seqs',
    name: 'RangedSeq',
    searchUrl: 'ranged-seqs',
    bundle: 'dev'
  },
  {
    idField: 'id',
    fixedColumns: 4,
    idType: 'uuid',
    titleField: 'name',
    delStrategy: 'delete',
    extEntity: false,
    description: '상세코드',
    association: 'one-to-many',
    active: false,
    dataProp: 'codes',
    tableName: 'common-code-details',
    masterId: '47a307c7-1574-46e8-8179-069ba57309fc',
    refField: 'parentId',
    name: 'CodeDetail',
    searchUrl: 'common-code-details',
    bundle: 'core'
  },
  {
    idField: 'id',
    multiSaveUrl: 'login_histories/update_multiple',
    idType: 'uuid',
    extEntity: false,
    name: 'LoginHistory',
    description: '로그인 이력',
    searchUrl: 'login-histories',
    bundle: 'sec',
    tableName: 'login-histories'
  },
  {
    idField: 'id',
    multiSaveUrl: 'user_role_histories/update_multiple',
    idType: 'uuid',
    extEntity: false,
    name: 'UserRoleHistory',
    description: '사용자 권한 이력',
    searchUrl: 'user-role-histories',
    bundle: 'sec',
    tableName: 'user-role-histories'
  },
  {
    idField: 'id',
    fixedColumns: 0,
    idType: 'uuid',
    titleField: 'name',
    delStrategy: 'restrict_with_error',
    extEntity: false,
    description: '커스텀 서비스 Input Parameters',
    association: 'one-to-many',
    active: false,
    tableName: 'service-in-params',
    masterId: 'cd519965-ab90-4d39-a263-316686e26dc0',
    refField: 'resourceId',
    name: 'ServiceInParam',
    searchUrl: 'service-in-params',
    bundle: 'dev'
  },
  {
    idField: 'id',
    fixedColumns: 0,
    idType: 'uuid',
    titleField: 'name',
    delStrategy: 'restrict_with_error',
    extEntity: false,
    description: '커스텀 서비스 Output Parameters',
    association: 'one-to-many',
    active: false,
    tableName: 'service-out-params',
    masterId: 'cd519965-ab90-4d39-a263-316686e26dc0',
    refField: 'resourceId',
    name: 'ServiceOutParam',
    searchUrl: 'service-out-params',
    bundle: 'dev'
  },
  {
    idField: 'id',
    multiSaveUrl: 'job_traces/update_multiple',
    fixedColumns: 3,
    idType: 'uuid',
    titleField: 'name',
    extEntity: false,
    description: 'Job 실행 이력',
    active: false,
    tableName: 'job-traces',
    name: 'JobTrace',
    searchUrl: 'job-traces',
    bundle: 'job'
  },
  {
    idField: 'id',
    multiSaveUrl: 'menus/{id}/menu_buttons/update_multiple',
    fixedColumns: 4,
    idType: 'uuid',
    titleField: 'name',
    delStrategy: 'delete',
    extEntity: false,
    description: '메뉴 버튼',
    association: 'one-to-many',
    active: false,
    dataProp: 'buttons',
    tableName: 'menu-buttons',
    masterId: 'edf11f36-ae31-4b01-af6e-60449ff7d24a',
    refField: 'menuId',
    name: 'MenuButton',
    searchUrl: 'menu/{id}/menu-buttons',
    bundle: 'base'
  },
  {
    idField: 'id',
    multiSaveUrl: 'jobs/update_multiple',
    fixedColumns: 3,
    idType: 'uuid',
    titleField: 'name',
    extEntity: false,
    description: 'Jobs for scheduler',
    active: false,
    tableName: 'jobs',
    name: 'Job',
    searchUrl: 'jobs',
    bundle: 'job'
  },
  {
    idField: 'id',
    multiSaveUrl: 'send_channels/update_multiple',
    fixedColumns: 3,
    idType: 'uuid',
    titleField: 'name',
    extEntity: false,
    description: '보내기 채널',
    active: false,
    tableName: 'send-channels',
    name: 'SendChannel',
    searchUrl: 'send-channels',
    bundle: 'sender'
  },
  {
    idField: 'id',
    multiSaveUrl: 'menu_details/update_multiple',
    fixedColumns: 4,
    idType: 'uuid',
    titleField: 'name',
    delStrategy: 'delete',
    extEntity: false,
    description: '메뉴 상세',
    association: 'one-to-many',
    active: false,
    dataProp: 'details',
    tableName: 'menu-details',
    masterId: 'edf11f36-ae31-4b01-af6e-60449ff7d24a',
    refField: 'menuId',
    name: 'MenuDetail',
    searchUrl: 'menu-details',
    bundle: 'base'
  },
  {
    idField: 'id',
    multiSaveUrl: 'menus/update_multiple',
    fixedColumns: 4,
    idType: 'uuid',
    titleField: 'name',
    delStrategy: 'delete',
    extEntity: false,
    description: '메뉴',
    active: false,
    tableName: 'menus',
    name: 'Menu',
    searchUrl: 'menus',
    bundle: 'base'
  },
  {
    idField: 'id',
    multiSaveUrl: 'user_histories/update_multiple',
    idType: 'uuid',
    extEntity: false,
    name: 'UserHistory',
    description: '사용자 계정 히스토리',
    searchUrl: 'user-histories',
    bundle: 'sec',
    tableName: 'user-histories'
  },
  {
    idField: 'id',
    multiSaveUrl: 'view_columns/update_multiple',
    fixedColumns: 0,
    idType: 'uuid',
    titleField: 'name',
    extEntity: false,
    description: 'Diy Form Column, Diy Grid Column 통합 테이블',
    active: false,
    tableName: 'view-columns',
    name: 'ViewColumn',
    searchUrl: 'view-columns',
    bundle: 'base'
  },
  {
    idField: 'id',
    multiSaveUrl: 'receive_channels/update_multiple',
    fixedColumns: 0,
    idType: 'uuid',
    titleField: 'name',
    extEntity: false,
    description: '받기 채널',
    active: false,
    tableName: 'receive-channels',
    name: 'ReceiveChannel',
    searchUrl: 'receive-channels',
    bundle: 'receiver'
  },
  {
    idField: 'id',
    multiSaveUrl: 'notices/update_multiple',
    fixedColumns: 3,
    idType: 'uuid',
    extEntity: false,
    description: '알림',
    active: false,
    tableName: 'notices',
    name: 'Notice',
    searchUrl: 'notices',
    bundle: 'stomp-cli'
  },
  {
    idField: 'id',
    multiSaveUrl: 'appr_docs/update_multiple',
    fixedColumns: 3,
    idType: 'uuid',
    titleField: 'name',
    extEntity: false,
    description: '결재 문서 인스턴스',
    active: false,
    tableName: 'appr-docs',
    name: 'ApprDoc',
    searchUrl: 'appr-docs',
    bundle: 'base'
  },
  {
    idField: 'id',
    multiSaveUrl: 'appr_lines/update_multiple',
    fixedColumns: 3,
    idType: 'uuid',
    titleField: 'name',
    extEntity: false,
    description: '결재 라인 마스터',
    active: false,
    tableName: 'appr-lines',
    name: 'ApprLine',
    searchUrl: 'appr-lines',
    bundle: 'base'
  },
  {
    idField: 'id',
    multiSaveUrl: 'appr_lines/{id}/appr_line_steps/update_multiple',
    fixedColumns: 3,
    idType: 'uuid',
    delStrategy: 'restrict_with_error',
    extEntity: false,
    description: '결재 라인 상세',
    association: 'one-to-many',
    active: false,
    tableName: 'appr-line-steps',
    refField: 'apprLineId',
    name: 'ApprLineStep',
    searchUrl: 'appr-lines/{id}/appr-line-steps',
    bundle: 'base'
  },
  {
    idField: 'id',
    multiSaveUrl: 'appr_tasks/update_multiple',
    fixedColumns: 0,
    idType: 'uuid',
    delStrategy: 'restrict_with_error',
    extEntity: false,
    description: '결재 문서 스텝별 히스토리',
    association: 'one-to-many',
    active: false,
    tableName: 'appr-tasks',
    refField: 'apprDocId',
    name: 'ApprTask',
    searchUrl: 'appr-tasks',
    bundle: 'base'
  },
  {
    idField: 'id',
    multiSaveUrl: 'procedures/update_multiple',
    fixedColumns: 3,
    idType: 'uuid',
    titleField: 'name',
    extEntity: false,
    description: '프로시저',
    tableName: 'procedures',
    name: 'Procedure',
    searchUrl: 'procedures',
    bundle: 'core'
  },
  {
    idField: 'id',
    multiSaveUrl: 'permit_urls/update_multiple',
    fixedColumns: 0,
    idType: 'uuid',
    extEntity: false,
    description: '접근 허용 URL',
    tableName: 'permit-urls',
    name: 'PermitUrl',
    searchUrl: 'permit-urls',
    bundle: 'sec'
  },
  {
    idField: 'id',
    multiSaveUrl: 'view_templates/update_multiple',
    fixedColumns: 3,
    idType: 'uuid',
    titleField: 'name',
    extEntity: false,
    description: 'Layout Template',
    active: false,
    tableName: 'view-templates',
    name: 'ViewTemplate',
    searchUrl: 'view-templates',
    bundle: 'screen'
  },
  {
    idField: 'id',
    multiSaveUrl: 'diy_forms/update_multiple',
    fixedColumns: 2,
    idType: 'uuid',
    titleField: 'name',
    extEntity: false,
    description: '커스텀 폼',
    active: false,
    tableName: 'diy-forms',
    name: 'DiyForm',
    searchUrl: 'diy-forms',
    bundle: 'screen'
  },
  {
    idField: 'id',
    multiSaveUrl: 'diy_grids/update_multiple',
    fixedColumns: 2,
    idType: 'uuid',
    titleField: 'name',
    extEntity: false,
    description: '커스텀 그리드',
    active: false,
    tableName: 'diy-grids',
    name: 'DiyGrid',
    searchUrl: 'diy-grids',
    bundle: 'screen'
  },
  {
    idField: 'id',
    multiSaveUrl: 'notifications/update_multiple',
    fixedColumns: 0,
    idType: 'uuid',
    titleField: 'name',
    extEntity: false,
    description: 'mobile 메시지 푸시',
    active: false,
    tableName: 'notifications',
    name: 'Notification',
    searchUrl: 'notifications',
    bundle: 'base'
  },
  {
    idField: 'id',
    multiSaveUrl: 'user_devices/update_multiple',
    fixedColumns: 0,
    idType: 'uuid',
    titleField: 'name',
    extEntity: false,
    description: '유저 모바일 디바이스 정보',
    active: false,
    tableName: 'user-devices',
    name: 'UserDevice',
    searchUrl: 'user-devices',
    bundle: 'base'
  },
  {
    idField: 'id',
    multiSaveUrl: 'appr_actions/update_multiple',
    fixedColumns: 3,
    idType: 'uuid',
    titleField: 'name',
    extEntity: false,
    description: '심사 승인 후 액션 정의',
    active: false,
    tableName: 'appr-actions',
    name: 'ApprAction',
    searchUrl: 'appr-actions',
    bundle: 'base'
  },
  {
    idField: 'id',
    multiSaveUrl: 'appr_action_traces/update_multiple',
    fixedColumns: 3,
    idType: 'uuid',
    titleField: 'name',
    extEntity: false,
    description: '심사 승인 후 액션 실행 이력',
    active: false,
    tableName: 'appr-action-traces',
    name: 'ApprActionTrace',
    searchUrl: 'appr-action-traces',
    bundle: 'base'
  },
  {
    idField: 'id',
    multiSaveUrl: 'favorites/update_multiple',
    fixedColumns: 0,
    idType: 'uuid',
    titleField: 'name',
    extEntity: false,
    description: '즐겨찾기',
    active: false,
    tableName: 'favorites',
    name: 'Favorite',
    searchUrl: 'favorites',
    bundle: 'base'
  },
  {
    idField: 'id',
    multiSaveUrl: 'alarms/update_multiple',
    fixedColumns: 4,
    idType: 'uuid',
    titleField: 'name',
    extEntity: false,
    description: '알람 설정 정의',
    active: false,
    tableName: 'alarms',
    name: 'Alarm',
    searchUrl: 'alarms',
    bundle: 'base'
  },
  {
    idField: 'id',
    multiSaveUrl: 'modbus/update_multiple',
    fixedColumns: 0,
    idType: 'uuid',
    extEntity: false,
    name: 'Modbus',
    description: '모드버스 프로토콜',
    active: true,
    searchUrl: 'modbus',
    bundle: 'base',
    tableName: 'modbus'
  },
  {
    idField: 'id',
    multiSaveUrl: 'settings/update_multiple',
    fixedColumns: 4,
    idType: 'uuid',
    titleField: 'name',
    extEntity: false,
    description: '설정',
    active: false,
    tableName: 'settings',
    name: 'Setting',
    searchUrl: 'settings',
    bundle: 'sys'
  },
  {
    idField: 'id',
    multiSaveUrl: 'error_logs/update_multiple',
    fixedColumns: 4,
    idType: 'uuid',
    extEntity: false,
    description: '에러 로그',
    active: false,
    tableName: 'error-logs',
    name: 'ErrorLog',
    searchUrl: 'error-logs',
    bundle: 'sys'
  },
  {
    idField: 'id',
    multiSaveUrl: 'users/update_multiple',
    fixedColumns: 4,
    idType: 'uuid',
    titleField: 'name',
    extEntity: false,
    description: '사용자',
    active: false,
    tableName: 'users',
    name: 'User',
    searchUrl: 'users',
    bundle: 'sys'
  },
  {
    idField: 'id',
    multiSaveUrl: 'domains/update_multiple',
    fixedColumns: 4,
    idType: 'auto-increment',
    titleField: 'name',
    extEntity: false,
    description: '도메인',
    active: false,
    tableName: 'domains',
    name: 'Domain',
    searchUrl: 'domains',
    bundle: 'sys'
  }
]
